language: java
jdk:
  - openjdk6
before_install:
  - sudo apt-get install -y sqlite3 mysql-server mysql-client p7zip
  - ( cd db ; make )
  - mysqladmin create openreact
  - mysql -uroot -Be 'GRANT ALL ON openreact.* TO openreact@localhost IDENTIFIED BY "openreact";'
  - mysql -uroot openreact -Be "SOURCE db/schema/000-schema.sql"
